base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
	
urlpatterns = [
	path('', views.home, name="index"),
	path('adminpage/', views.adminpanel, name="admin"),
    path('add_product/', views.add_product, name="add_product"),
	path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
	path('form/', views.form, name="form"),
	path('login/', views.signin, name="login"),
  path('logout/', views.user_logout, name='user_logout'),
	path('profile/', views.profile, name="profile"),
	path('update_user/', views.update_user, name="update_user"),
	path('update_info/', views.update_info, name="update_info"),
	path('reciept/', views.reciept, name="reciept"),
	path('register/', views.register, name="register"),
	path('shop/', views.shop, name="shop"),
	path('utilities_animation/', views.utilities_animation, name="utilities_animation"),
 path('item_item/', views.item_item, name="item_item"),
 path('user_user/', views.user_user, name="user_user"),
path('set-default-address/<int:address_id>/', views.set_default_address, name='set_default_address'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),


]

base/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    phone = models.CharField(max_length=20, blank=True)
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=255, blank=True)
    zipcode = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    old_cart = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
#Create user profile
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
#automate
post_save.connect(create_profile, sender=User)



class Customer (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    total_spent = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username
    
class DeliveryAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="addresses")
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100, default="Philippines")
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.address_line1}, {self.city} ({'Default' if self.is_default else 'Secondary'})"

    def save(self, *args, **kwargs):
        # Ensure only one address is marked as default
        if self.is_default:
            DeliveryAddress.objects.filter(customer=self.customer, is_default=True).update(is_default=False)
        super().save(*args, **kwargs)

    
class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Shoes")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"
    
    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50">' % (self.image.url))

    def __str__(self):
        return self.title

class Product(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, default=0)
    description = models.CharField(max_length=250, blank=True, null=True)
    image = models.ImageField(upload_to='', max_length=100, blank=True, null=True)
    def __str__(self):
        return self.name

templates/admin.html
{% extends 'partials/base-admin.html' %}
{% load static %}

{% block content %}  
       <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column" >

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="pt-5 mb-4">
                        <h1 class="h3 mb-0 text-gray-800 text-center">My Dashboard</h1>
                    </div>

                    <!-- Content Row -->
                    <div class="row">



                        <!-- Earnings (Monthly) Card Example -->
                        

                        <!-- Pending Requests Card Example -->

                    </div>


                <div class="container-fluid red-text">

                    <!-- DataTales Example -->
                    <div class="card mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 text-warning text-center red-text">Users</h6>
                        </div>
                        <div class="text-warning red-text">
                            <div class="">
                                <table class="table table-striped text-warning red-text" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone Number</th>
                                            <th>Location</th>
                                            <th>Total amount spent</th>
                                        </tr>
                                    </thead>
                               
                                    <tbody>
                                        
                                        {% for user in users %}
                                        {% if not user.is_superuser %}
                                        <tr>
                                            <td>{{ user.first_name }} {{ user.last_name }}</td>
                                            <td>{{ user.email }}</td>
                                            <td>{{ user.customer.phone_number }}</td>
                                            <td>{{ user.customer.location }}</td>
                                            <th>₱{{ user.customer.total_spent }}</th>
                                        </tr>
                                        {% endif %}
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-2 col-md-6 mb-4 text-center">
                        <div class=" h-100 py-2">
                            <div class="">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2 red-text">
                                        <div class="text-xs font-weight-bold text-dark text-uppercase mb-1 red-text ">
                                            Overall earnings this time:</div>
                                            <div class="h5 mb-0 text-lg text-warning red-text">₱{{ total_spent }}</div>
                                    </div>
                                    <div class="col-auto">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-2 col-md-6 mb-4 text-center">
                        <div class=" h-100 py-2">
                            <div class="">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-dark text-uppercase mb-1 red-text">
                                            Overall users this time:</div>
                                            <div class="h5 mb-0 text-lg text-warning red-text">{{ total_users }}</div>
                                    </div>
                                    <div class="col-auto">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>

                

                {% comment %} <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Users</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Order Number</th>
                                            <th>Product name</th>
                                            <th>Buyer</th>
                                            <th>Location</th>
                                            <th>Total amount</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        
                                        {% for shopping_cart in shopping_carts %}
                                        <tr>
                                            <td>{{ shopping_cart.id }}</td>
                                            <td>{{ shopping_cart.cart_item.name }}</td>
                                            <td>{{ shopping_cart.user.first_name }} {{ shopping_cart.user.last_name }}</td>
                                            <td>{{ shopping_cart.user.location }}</td>
                                            <td>₱{{ shopping_cart.cart_item_total }}</td>
                                            <td>
                                                <select class="form-control" id="status" name="status" value="{{ shopping_cart.cart_status }}" style="width: 150px;" disabled>
                                                    <option value="1" {% if shopping_cart.cart_status == 1 %}selected{% endif %}>Pending</option>
                                                    <option value="2" {% if shopping_cart.cart_status == 2 %}selected{% endif %}>On delivery</option>
                                                    <option value="3" {% if shopping_cart.cart_status == 3 %}selected{% endif %}>Complete</option>
                                                  </select>
                                            </td>
                                            {% if shopping_cart.cart_status == 3 %}
                                            <td>Delivered</td>
                                            {% elif shopping_cart.cart_status == 1 %}
                                            <td>Waiting for confirmation</td>
                                            {% else %}
                                            <td><a href="{% url 'update_cart_status' shopping_cart_id=shopping_cart.id %}"><button class="btn-success">Product delivered</button></a></td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div> {% endcomment %}

                <!-- Begin Page Content -->
                {% comment %} <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Users</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone Number</th>
                                            <th>Location</th>
                                            <th>Total amount spent</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone Number</th>
                                            <th>Location</th>
                                            <th>Total amount spent</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        
                                        {% for user in users %}
                                        {% if not user.is_superuser %}
                                        <tr>
                                            <td>{{ user.first_name }} {{ user.last_name }}</td>
                                            <td>{{ user.email }}</td>
                                            <td>{{ user.customer.phone_number }}</td>
                                            <td>{{ user.customer.location }}</td>
                                            <th>₱{{ user.customer.total_spent }}</th>
                                        </tr>
                                        {% endif %}
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div> {% endcomment %}
                <!-- /.container-fluid -->
                                <!-- Begin Page Content -->
                                
                                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
                

                  
            <!-- Footer -->
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Logout Modal-->
    {% endblock %}

templates/edit_product.html
<!DOCTYPE html>
<html>
  <head>
    <title>product form</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <style>
      /* Reset default styles */
      html, body {
        display: flex;
        justify-content: center;
        height: 100%;
      }
      body {
        background-color: rgb(157, 4, 4);
        padding: 20px;
      }
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        outline: none;
      }
      /* Typography */
      body, input, button {
        font-family: 'Poppins', sans-serif;
        font-size: 16px;
        color: #333;
        font-weight: 400;
        line-height: 1.5;
      }
      h1 {
        font-size: 36px;
        font-weight: 500;
        text-align: center;
        margin-bottom: 20px;
      }
      /* Form styles */
      .main-block {
        max-width: 500px;
        margin: auto;
        border-radius: 10px;
        box-shadow: 1px 2px 5px rgba(0,0,0,.2);
        background-color: #fff;
        padding: 40px;
      }
      form {
        margin-top: 20px;
      }
      hr {
        border: 0;
        border-top: 1px solid #ccc;
        margin: 30px 0;
      }
      input {
        display: block;
        width: 100%;
        height: 40px;
        padding: 10px;
        margin: 10px 0;
        border-radius: 5px;
        border: 1px solid #ccc;
        transition: border-color 0.3s;
      }
      input:focus {
        border-color: #1c87c9;
        outline: none;
      }
      .btn-block {
        text-align: center;
        margin-top: 30px;
      }
      button {
        display: inline-block;
        width: 200px;
        height: 50px;
        background-color: #1c87c9;
        color: #fff;
        font-size: 18px;
        font-weight: 600;
        border-radius: 5px;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s;
      }
      button:hover {
        background-color: #26a9e0;
      }
    </style>
  </head>
  <body>
    <div class="main-block">
      <h1>Edit product</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="product_name" id="product_name" placeholder="Name" value="{{ product.name }}" required/>
        <input type="number" name="product_quantity" id="product_quantity" placeholder="Quantity" value="{{ product.quantity }}" required/>
        <input type="number" name="product_price" id="product_price" placeholder="Price in ₱" value="{{ product.price }}" required/>
        <label for="description"><h3>Description:</h3></label>
        <textarea id="product_description" name="product_description" rows="4" cols="43" placeholder="Enter a product description" required>{{ product.description }}</textarea>
        <br>
        <!-- Add a radio button or a checkbox for the user to choose whether they want to update the image or not -->
        <label for="update_image">Check the box to update image:</label>
        <input type="checkbox" name="update_image" id="update_image">
        Current Image:
        <img src="{{ product.image.url }}" id="image-preview" width="300" height="200" style="display: block; margin: auto;">
        <label for="image"><h3>Image:</h3></label>
        <input type="file" name="image" id="image" accept="image/*">
        <hr>
        <div class="btn-block">
            <button type="submit">Submit</button>
        </div>
      </form>
      
    
    
    </div>
  </body>
</html>

templates/form.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <title>Educational registration form</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">
    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, p { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: 'Poppins', sans-serif;
      font-size: 16px;
      color: #eee;
      }
      body {
      background-color: rgb(238, 64, 64);
      background-size: cover;
      }
      h1, h2 {
      text-transform: uppercase;
      font-weight: 400;
      }
      h2 {
      margin: 0 0 0 8px;
      }
      .main-block {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      height: 100%;
      padding: 25px;
      background: rgba(0, 0, 0, 0.5); 
      }
      .left-part, form {
      padding: 25px;
      }
      .left-part {
      text-align: center;
      }
      .fa-graduation-cap {
      font-size: 72px;
      }
      form {
      background: rgba(0, 0, 0, 0.7); 
      }
      .title {
      display: flex;
      align-items: center;
      margin-bottom: 20px;
      }
      .info {
      display: flex;
      flex-direction: column;
      }
      input, select {
      padding: 5px;
      margin-bottom: 30px;
      background: transparent;
      border: none;
      border-bottom: 1px solid #eee;
      }
      input::placeholder {
      color: #eee;
      }
      option:focus {
      border: none;
      }
      option {
      background: black; 
      border: none;
      }
      .checkbox input {
      margin: 0 10px 0 0;
      vertical-align: middle;
      }
      .checkbox a {
      color: #26a9e0;
      }
      .checkbox a:hover {
      color: #85d6de;
      }
      .btn-item, button {
      padding: 10px 5px;
      margin-top: 20px;
      border-radius: 5px; 
      border: none;
      background: #26a9e0; 
      text-decoration: none;
      font-size: 15px;
      font-weight: 400;
      color: #fff;
      }
      .btn-item {
      display: inline-block;
      margin: 20px 5px 0;
      }
      button {
      width: 100%;
      }
      button:hover, .btn-item:hover {
      background: #85d6de;
      }
      @media (min-width: 568px) {
      html, body {
      height: 100%;
      }
      .main-block {
      flex-direction: row;
      height: calc(100% - 50px);
      }
      .left-part, form {
      flex: 1;
      height: auto;
      }
      
      }
    </style>
  </head>
  <body>
    <div class="main-block">
      <div class="left-part">
        <i class="fas fa-graduation-cap"></i>
        <h1>HERMES: Mechanical Product</h1>
        <p>Random bullshit dili ko knows anong ilagay ko here kase pakyu ka khen</p>
      
      </div>
      <form action="/">
        <div class="title">
          <i class="fas fa-pencil-alt"></i> 
          <h2>Checkout</h2>
        </div>
        <div class="info">
            
          <p>Full name:</p>
          <input class="fname" type="text" name="name" placeholder="" required>
          <p>Email:</p>
          <input type="email" name="name" placeholder="" required>
          <p>Phone Number:</p>
          <input type="number" name="name" placeholder="" required>
          <p>Location:</p>
          <input type="text" name="name" placeholder="Street Address/City/ZIP code/Barangay" required>

        </div>
        <div class="checkbox" aria-required="true">
          <input type="checkbox" name="checkbox"><span>I agree to the <a href="#">Privacy Policy of HERMES: Mechanical Parts.</a></span>
        </div>

      <a href="{% url 'reciept' %}">
        <button type="button">Submit</button>
      </a>
      </form>
    </div>
  </body>
</html>

templates/index.html
{% extends 'partials/base.html' %}
{% load static %}


{% block content %}
<main>
    <article>

      <!-- 
        - #HERO
      -->

      <section class="section hero" style="background-image: url('/static/image/herobanner.png')">
        <div class="container">

          <h2 class="h1 hero-title">
            New Stocks <strong>Shoes Collection</strong>
          </h2>

          <p class="hero-text">
            Discover Hood: the ultimate destination for shoe enthusiasts. Elevate your style with our curated collection, blending quality craftsmanship and urban flair. Step into the future of footwear fashion with Hood.
          </p>

          <button class="btn btn-primary">
            <span>Shop Now</span>

            <ion-icon name="arrow-forward-outline" aria-hidden="true"></ion-icon>
          </button>

        </div>
      </section>


<!-- CAROUSEL-->
<section class="carousel">
<div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="2000">
      <div class="overlay-image" style="background-image: url(/static/image/carousel-slide1.jpg);">

    </div>
      <div class="carousel-caption d-none d-md-block">

      </div>
    </div>
    <div class="carousel-item active" data-bs-interval="2000">
      <div class="overlay-image" style="background-image: url(/static/image/carousel-slide2.jpg);">
  
    </div>
      <div class="carousel-caption d-none d-md-block">

      </div>
    </div>
    <div class="carousel-item active" data-bs-interval="2000">
      <div class="overlay-image" style="background-image: url(/static/image/carousel-slide3.jpg);">

    </div>
      <div class="carousel-caption d-none d-md-block">

      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</section>
      <!-- 
        - #COLLECTION
      -->
      <section class="section collection">
        <div class="container">
          <h1 class="text-center mb-4">Our Categories</h1>
          <ul class="collection-list has-scrollbar">

            <li>
              <div class="collection-card" style="background-image: url('/static/image/collection-1.jpg')">
                <h3 class="h4 card-title">Men Collections</h3>




                </a>
              </div>
            </li>

            <li>
              <div class="collection-card" style="background-image: url('/static/image/collection-2.jpg')">
                <h3 class="h4 card-title">Women Collections</h3>


                </a>
              </div>
            </li>

            <li>
              <div class="collection-card" style="background-image: url('/static/image/collection-3.jpg')">
                <h3 class="h4 card-title">Sports Collections</h3>


                </a>
              </div>
            </li>

          </ul>

        </div>
      </section>






      
      <h1 class="text-center mb-4">Our Products</h1>
<div class="container border border-danger rounded p-4 bg-white">
  {% for product in products %}
    {% if forloop.counter0|divisibleby:3 %}
      <div class="row">
    {% endif %}
      <div class="col-md-4">
        <div class="product p-3 mb-3 bg-light border rounded">
          <div class="product-image-container">
            <img src="{{ product.image.url }}" class="img-fluid product-image" alt="Product Image">
          </div>
          <h2>{{ product.title }}</h2> <!-- Use product.title instead of p.title -->
          <p>{{ product.description }}</p>
          <p style="color: black;">₱ {{ product.price }}</p>
          {% if user.is_authenticated %}
            <a href="{% url 'shop' %}" class="btn btn-sm btn-dark px-3">Buy Now</a>
          {% else %}
            <a href="{% url 'login' %}" class="btn btn-sm btn-primary px-3">Buy Now</a>
          {% endif %}
        </div>
      </div>
    {% if forloop.counter|divisibleby:3 or forloop.last %}
      </div>
    {% endif %}
  {% endfor %}
</div>



<!---->
    
<!-- Package End -->

    <!-- Footer End -->


    <!-- Back to Top -->
    {% comment %} <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a> {% endcomment %}

{% endblock %}

templates/shop.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
    
  <br><br><br><br>
  <h1 class="text-center mb-4">Our Products</h1>
  
  
  <!--START OF PRODUCT LIST-->
  <div class="container-xxl py-5">
    <div class="container">
      <div class="row g-4 justify-content-center">
        {% for category in categories %}
        <h1 class="text-left mb-4" style="padding-left: 80px;">{{ category.title }}</h1>
        <div class="container border border-danger rounded p-4 bg-white">
          {% for product in category.product_set.all %}
            {% if forloop.counter0|divisibleby:3 %}
              <div class="row">
            {% endif %}
            <div class="col-md-4">
              <div class="product p-3 mb-3 bg-light border rounded">
                <div class="product-image-container">
                  <img src="{{ product.image.url }}" class="img-fluid product-image" alt="Product Image">
                </div>
                <h2>{{ product.name }}</h2>
                <p>{{ product.description }}</p>
                <p>₱ {{ product.price }}</p>
                <div class="row">
                  <div class="col-md-2">Quantity:</div>
                  <div class="col-md-2">
                <select class="form-select form-select-sm" id="qty-cart">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                </select>
              </div>
              </div>
                {% if user.is_authenticated %}
                <button type="button" value="{{ product.id }}" class="btn btn-secondary add-cart">Add to Cart</button>

            {% else %}
                <a href="{% url 'login' %}" class="btn btn-sm btn-primary px-3">Buy Now</a>
            {% endif %}
              </div>
            </div>
            {% if forloop.counter|divisibleby:3 or forloop.last %}
              </div>
            {% endif %}
          {% endfor %}
        </div>
      {% endfor %}
      </div>
    </div>
  </div>





{% endblock %}